### ISSUE TITLE
Code copied from PythonProgramming.net

### ISSUE THREAD

**Issue by ghost** [akshaybahadur21/FaceDetection#1]
Hello Akshay, 

The code is exactly same to the actual tutorial by sentdx in his python programming tutorial website and can be obtained at this [link](https://pythonprogramming.net/haar-cascade-face-eye-detection-python-opencv-tutorial/). 

It is healthy to learn through the tutorial and apply the knowledge to work on an new idea, but copying someone's work and tagging it with your name is not professional and is termed as stealing. 

Sid

**Comment by akshaybahadur21** [comment]
Hi @Sidhant-Chatterjee ,
Sorry about that.
I was pretty naive when I worked on it.
Added references for the same in readme.md
